services:
- type: web
  name: smart-energy-ui
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "streamlit run st_app.py"
  envVars:
  - key: STREAMLIT_ENV
    value: production
  - key: PORT
    value: "8501"
